services:

  # Conteneur MongoDB
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27018:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_ID}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PW}

      MONGO_DB: ${MONGO_DB}

      MONGO_USER_ADMIN_ID: ${MONGO_USER_ADMIN_ID}
      MONGO_USER_ADMIN_PW: ${MONGO_USER_ADMIN_PW}

      MONGO_USER_VISITOR_ID: ${MONGO_USER_VISITOR_ID}
      MONGO_USER_VISITOR_PW: ${MONGO_USER_VISITOR_PW}

    volumes:
      - mongodb_data:/data/db      # volume pour persister la base de données
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js  # script de création des utilisateurs

  # Conteneur qui exécute la migration
  migration:
    build: .
    container_name: migration
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://${MONGO_USER_ADMIN_ID}:${MONGO_USER_ADMIN_PW}@mongodb:27017/${MONGO_DB}
    volumes:
      - ./data:/app/data
    command: python migrate.py

volumes:
  mongodb_data:                    # volume nommé pour les données MongoDB
